name: CI

on:
  # We run CI on pushes to the main branch
  push:
    branches:
      - main
  # and on all pull requests to the main branch
  pull_request:
    branches:
      - main
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  build-and-test:
    name: Testing on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Here, we are testing the oldest and the newest supported Python version.
        # If this is insufficient for your package, consider adding more versions.
        python-version: ["3.8", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # setuptools_scm requires a non-shallow clone of the repository
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python package
      run: |
        python -m pip install .[tests]
    
   # - name: Run Python tests
   #   run: |
   #     python -m pytest --nbval

  coverage:
    name: Coverage Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"

    - name: Install Python package
      run: |
        python -m pip install .[tests]

    - name: Run Python tests
      working-directory: ./tests
      run: |
        python -m pytest --cov --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        files: ./tests/coverage.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
